# Base image
FROM python:3.10-slim

# Set working directory
WORKDIR /backend

# Copy backend-related files
COPY app.py .
COPY preprocessing_pipeline.joblib .
COPY xgb_model.joblib .
COPY preprocessing.py .
COPY requirements.txt .

# Install required libraries
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 8000 for FastAPI
EXPOSE 8000

# Run the FastAPI app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]