# Base image
FROM python:3.10-slim

# Set working directory
WORKDIR /frontend

# Copy frontend-related files
COPY streamlit_app.py .
COPY requirements.frontend.txt .

# Install required libraries
RUN pip install --no-cache-dir -r requirements.frontend.txt

# Expose port 8501 for Streamlit
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
